課題をやりました
flutteruniv/hoiqoo pull request #8
Opened 2022-11-04 17:06 UTC by Fukushin-0129

## やったこと
　背景をグレーにした
　中央に配置した
　自分の名前の文字を大きくした。
　Slackのアイコンを貼り付けて、画面サイズの2分の１のサイズにした。

## スクリーンショット

## 動作確認
* [] 

## その他
レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2022-11-05 06:58 UTC, HiroMinase requested changes
ところどころインデントがずれているように見えるので、見直してみてください🌿
他の人のPRを見るのも参考になると思います！

2022-11-05 06:58 UTC, HiroMinase commented on lib/fukushin.dart
> +        color:Colors.grey,
ほかと合わせて `:` の後ろに半角スペースをお願いします🙏🏻

2022-11-05 06:58 UTC, HiroMinase commented on lib/main.dart
> +      title: 'hoiq Ap',
不要な変更が混ざっていので削除をお願いします🙏🏻

2022-11-05 06:58 UTC, HiroMinase commented on pubspec.yaml
> +     -images/fukushin.heic
この画像ファイルは使用していますか？

2022-11-05 08:14 UTC, Fukushin-0129 commented on lib/fukushin.dart
> +        color:Colors.grey,
修正したつもり

2022-11-05 08:14 UTC, Fukushin-0129 commented on lib/main.dart
> +      title: 'hoiq Ap',
修正したつもり

2022-11-05 08:15 UTC, Fukushin-0129 commented on pubspec.yaml
> +     -images/fukushin.heic
使用してないので削除します。

2022-11-06 09:27 UTC, HiroMinase reviewed
概要欄の記入もお願いします 🙏

2022-11-06 09:27 UTC, HiroMinase commented on pubspec.yaml
> -
不要な変更は含めないようにしましょう〜！

2022-11-06 09:27 UTC, HiroMinase commented on lib/fukushin.dart
>  }
この下に空行を用意してほしい時に表示されるマークですね 🙏

2022-11-06 09:27 UTC, HiroMinase commented on lib/fukushin.dart
> +         child: Column(
ここ1つしかスペース置けてないですかね...!!

2022-11-06 09:27 UTC, HiroMinase commented on lib/fukushin.dart
> +                  ),
ここもインデントがずれていますね 🙏

2022-11-06 09:27 UTC, HiroMinase commented on lib/fukushin.dart
> +          ]),
細かいですがここもまとめて書くより複数行に分けた方がカッコの組み合わせが分かりやすそうです！

2022-11-08 22:43 UTC, Fukushin-0129 commented on pubspec.yaml
> -
# The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
を消したのですが、これでよかったんでしょうか。

2022-11-08 22:44 UTC, Fukushin-0129 commented on lib/fukushin.dart
>  }
やってみたつもりですが。大丈夫でしょうか？

2022-11-08 22:47 UTC, Fukushin-0129 commented on lib/fukushin.dart
> +         child: Column(
child の前にスペース加えました。

2022-11-08 22:48 UTC, Fukushin-0129 commented on lib/fukushin.dart
> +                  ),
修正しました。

2022-11-08 22:52 UTC, Fukushin-0129 commented on lib/fukushin.dart
> +          ]),
こんな感じでしょうか

2022-11-08 22:54 UTC, Fukushin-0129 commented
チームで作る時には、わかりやすいコードの書き方が必要なんですね。
勉強になります

2022-11-09 10:24 UTC, HiroMinase requested changes
`images/fukushin.heic` を使っていないのであれば消しましょうか 🙏

2022-11-09 10:24 UTC, HiroMinase commented on pubspec.yaml
> -
@Fukushin-0129 これはどういう意図で消しましたか？

2022-11-09 10:24 UTC, HiroMinase commented on lib/fukushin.dart
> +                ),
ここ1段上ですね 🙏

2022-11-09 10:24 UTC, HiroMinase commented on lib/fukushin.dart
>            // TODO: childrenに含まれる各要素を画面の上下左右中央に配置してください
ここは1段下ですね！

2022-11-09 15:03 UTC, Fukushin-0129 commented on pubspec.yaml
> -
不要な変更は含めないようにしましょう〜がよく分からなかったので、消しました

2022-11-09 15:10 UTC, Fukushin-0129 commented on lib/fukushin.dart
> +                ),
３７行目のことですか？修正しました。

2022-11-09 15:12 UTC, Fukushin-0129 commented on lib/fukushin.dart
>            // TODO: childrenに含まれる各要素を画面の上下左右中央に配置してください
//TODOのところですか？修正しました。

2022-11-09 15:15 UTC, Fukushin-0129 commented
こんな感じでしょうか？

2022-11-10 15:36 UTC, HiroMinase approved these changes
インデントも綺麗になりましたね！！お疲れ様でした 🎉

2022-11-10 15:37 UTC, merged